---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: worker
- role: control-plane
  kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      apiServer:
        extraArgs:
          oidc-issuer-url: 'https://vault.local/v1/identity/oidc/provider/k8s-oidc-provider'
          # this needs to be adapted to the generated client id of the vault oidc client
          oidc-client-id: VdR3979Qwa2CRCtljFoFgWSuIItmXGc6
          oidc-username-claim: alias
          oidc-groups-claim: groups
          oidc-username-prefix: 'vault:'
          oidc-groups-prefix: 'vault:'
  extraMounts:
  - hostPath: ./rootCA.pem
    containerPath: /usr/local/share/ca-certificates/mkCertRootCA.crt
